spring:
  datasource:
    url: jdbc:mysql://database-1.cmscnmfxtv9h.us-west-2.rds.amazonaws.com:3306/asialink?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: lycwyx20151012!
    driver-class-name: com.mysql.cj.jdbc.Driver
